homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    switch:
      assumed_state: true

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

ios:

http:
  api_password: !secret http_password
  base_url: https://yedgar.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Cloud
cloud:

vera:
  vera_controller_url: http://10.100.102.200:3480
  
mqtt:
  broker: m23.cloudmqtt.com
  port: 16080
  username: !secret mqtt_user
  password: !secret mqtt_password

#telegram  
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_chat

notify:
  - name: bot_bot
    platform: telegram
    chat_id: !secret telegram_chat
#end telegram


switch:
  - platform: command_line
    switches:
      living_room_aircon_protected:
        command_on: "pwd"
        command_off: "pwd"
      test2:
        command_on: "pwd"
        command_off: "pwd"

  - platform: broadlink
    host: 10.100.102.20
    mac: '34:ea:34:42:aa:3b'
    type: rm_mini
    switches:
      parents_air_con:
        friendly_name: "Parents Air Condition"
#heat
        command_on: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
        command_off: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
#cold
#        command_on: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
#        command_off: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
      
      parents_fan:
        friendly_name: "Parents Fan"
        command_on: 'JgCgAS0LLAsRJywLLAwQJxAoECcsCxEnECcQAAEFLAwsCxAoLAssCxEnECcQKCwLECgQJxAAAQUsCywMECcsDCwLECgQJxAnLAwQJxAoEAABBSwLLAwQJywMKwwQJxAoECcsDBAnECcQAAEFLAwsCxAoLAssCxEnECcQKCwLECgQJxAAAQUsCywMECcsDCwLECgQJxAnLAwQJxEnEAABBSwLLAwQJywLLAwQJxAoECcsCxEnECcQAAEFLAwrDBAoKwwsCxAoECcQKCsMECcQKBAAAQUrDCwMECcsDCsMECcQKBAnLAwPKBAnEAABBSwMKw0PKCsMLAwOKQ8oDykqDQ8pDygPAAEGKw0qDQ8oKw0qDQ8pDygPKSoNDygPKQ8AAQYqDSsNDikrDSoODigPKQ8oKw0OKQ4qDQABByoOKQ8NKikOKg8MKg4qDSopDw0qDSoOAAEHKg4pDg4qKQ8oDg4qDSoOKikPDSkOKg4AAQcpDykODSoqDikPDSkOKg0qKg4NKg4qDQABCCkPKA8NKikPKQ8MKg4qDSopDg4qDSoOAA0FAAAAAAAAAAA='
        command_off: 'JgBSASkPKQ4NKikQKA4OKQ4qDSoOKg0qDiop6yoOKQ4OKikPKQ8MKg4qDSoNKg4qDSop7CoPKA8NKikOKQ8NKg0qDioNKg4pDiop7CkOKg8MKikPKQ4OKQ4qDSoOKg0qDikq6yoPKA8NKikPKg0OKQ8oDykPKA8pDikr6isNKg0PKCsNKg0PKQ4pDygPKQ8oECgr6isMLAwPKCwLLAwQJxAoECcQJxAoECcs6SwMLAsQKCsMLAwQJxAnEScQJxAoECcs6SwMLAsQJywMLAsQKBAnECgQJxAnEScs6SwLLAwQJywMKwwQJxEnECcQKBAnECcs6SwMLAsRJywLLAwQJxAnECgQJxAoECcs6SwLLAwQJywMKwwQJxAoECcQKA8oECgq6isNKw0OKSoNKw4OKA8pDikPKA8pDygr6isNKg0PKCsNKg0PKQ8oDykOKQ8oDykqAA0FAAAAAAAA'

  - platform: broadlink
    host: 10.100.102.21
    mac: '34:ea:34:42:b6:46'
    type: rm_mini
    switches:
      kids_air_con:
        friendly_name: "Kids Air Condition"
#heat
        command_on: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
        command_off: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
#cold
#        command_on: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
#        command_off: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
      kids_fan:
        friendly_name: "Kids Fan"
        command_on: 'JgCgAS0LLAsRJywLLAwQJxAoECcsCxEnECcQAAEFLAwsCxAoLAssCxEnECcQKCwLECgQJxAAAQUsCywMECcsDCwLECgQJxAnLAwQJxAoEAABBSwLLAwQJywMKwwQJxAoECcsDBAnECcQAAEFLAwsCxAoLAssCxEnECcQKCwLECgQJxAAAQUsCywMECcsDCwLECgQJxAnLAwQJxEnEAABBSwLLAwQJywLLAwQJxAoECcsCxEnECcQAAEFLAwrDBAoKwwsCxAoECcQKCsMECcQKBAAAQUrDCwMECcsDCsMECcQKBAnLAwPKBAnEAABBSwMKw0PKCsMLAwOKQ8oDykqDQ8pDygPAAEGKw0qDQ8oKw0qDQ8pDygPKSoNDygPKQ8AAQYqDSsNDikrDSoODigPKQ8oKw0OKQ4qDQABByoOKQ8NKikOKg8MKg4qDSopDw0qDSoOAAEHKg4pDg4qKQ8oDg4qDSoOKikPDSkOKg4AAQcpDykODSoqDikPDSkOKg0qKg4NKg4qDQABCCkPKA8NKikPKQ8MKg4qDSopDg4qDSoOAA0FAAAAAAAAAAA='
        command_off: 'JgBSASkPKQ4NKikQKA4OKQ4qDSoOKg0qDiop6yoOKQ4OKikPKQ8MKg4qDSoNKg4qDSop7CoPKA8NKikOKQ8NKg0qDioNKg4pDiop7CkOKg8MKikPKQ4OKQ4qDSoOKg0qDikq6yoPKA8NKikPKg0OKQ8oDykPKA8pDikr6isNKg0PKCsNKg0PKQ4pDygPKQ8oECgr6isMLAwPKCwLLAwQJxAoECcQJxAoECcs6SwMLAsQKCsMLAwQJxAnEScQJxAoECcs6SwMLAsQJywMLAsQKBAnECgQJxAnEScs6SwLLAwQJywMKwwQJxEnECcQKBAnECcs6SwMLAsRJywLLAwQJxAnECgQJxAoECcs6SwLLAwQJywMKwwQJxAoECcQKA8oECgq6isNKw0OKSoNKw4OKA8pDikPKA8pDygr6isNKg0PKCsNKg0PKQ8oDykOKQ8oDykqAA0FAAAAAAAA'
      kids_light:
        friendly_name: "Kids Light"
        command_on: 'JgAEASsMKg4OKSwMKg0OKisNDSoQJxAoECgPAAEGLAwrDBAoKwwqDg4qKwwOKg8oDykPKBAAAQYrDCwMDiksDCoNDiorDQ8oECgPKBAoDwABBiwMKQ4QKCsMKg4QJywMECcQKBAoDygQAAEGKwwqDhAnLAwqDQ4qKw0PKBAoDygQKA8AAQYsDCoNDiorDCoODiksDA4qDygQKA8oEAABBisMKg4OKSwMKg4NKiwMDSoQKA8oECgPAAEGLAwqDQ4qKw0pDg4pLAwOKg8oECgPKBAAAQYrDCoODiksDCoODSorDQ0qECgQJxAoDwABBiwMKg0OKisNKQ4OKikODioPKBEnDygQAA0FAAAAAA=='
        command_off: 'JgDyACwMLAsQKCwMLAssDBAnECgQJxAoKwws6iwLLQsQJywMLAssDBAoECcRJxAnLAws6SwMLAsQKCwLLQssDBAnECgQKBAnKw0r6iwMLAsQJywMLAssDBEnECcRJxAoLAos6iwMLAwQJy0KLAwtChEnECgQJxAoLAss6iwLLAwQJywMLAssDBAoECcQKBAnLAwr6iwMLAsQKCwLLAwsDBAnECgQJxAoLAss6iwLLQoRKC0JLQwtChEnECcRJxAnLAwt6CwMLQoRJywLLQssDBAnECgQKBAnLAws6SwMKwwRJiwMLAwrDBEnECcQKBAoKwwrAA0FAAAAAAAA'
        
  - platform: broadlink
    host: 10.100.102.22
    mac: '34:ea:34:42:b6:56'
    type: rm_mini
    switches:
      living_room_air_con:
        friendly_name: "Living Room Air Condition"
#heat
        command_on: 'JgC4AGaBQD9AQCEfQR8fISEfIR8hPyAfIR8hH0EfHiEiHyAfIR8hHx8hHyAhHyEfIR8iHyAfIR8gICEfID9CH2CCQj9APyEfQR8hHiIeIR8fQSEfHyEfIUEeIh8fICIfIB8iHyAgICAgHiIfIR8fICEfICAfISEgID5AIGSBQD9BPyAfQCAiHyAfHyAgQCEfHyEfIUEfHyAgICAgIh8eIR8hHyEfIR8gIh8gHyIfHyAiHyEeH0BBH4MADQU=='
        command_off: 'JgC4AGaBQD9AQCEfQR8fISEfIR8hPyAfIR8hH0EfHiEiHyAfIR8hHx8hHyAhHyEfIR8iHyAfIR8gICEfID9CH2CCQj9APyEfQR8hHiIeIR8fQSEfHyEfIUEeIh8fICIfIB8iHyAgICAgHiIfIR8fICEfICAfISEgID5AIGSBQD9BPyAfQCAiHyAfHyAgQCEfHyEfIUEfHyAgICAgIh8eIR8hHyEfIR8gIh8gHyIfHyAiHyEeH0BBH4MADQU=='
#cold
#        command_on: 'JgC+AGSCQB8gQT8gHyEfISAgICAgIB8gIEAgIEAfICAgICAgICEfIB8hICAfICAgICAfIR8hICEfICAgHyEfQD8hYoFAICBAQCEeISAgICAfIR8hHyAfQSAhPiEfICEfISAeISAgHyEgICAfICAgICAgICEeIR8iHiEgICA/QCFggz8gIEA/Ih4hICAfICAgISAfICBBHyA/ISAfICAgICAgICEeIR8iHyAgIB8gISAeISAhHyEeIR8gIEBAIIEADQUAAAAAAAAAAAAA'
#        command_off: 'JgC+AGSCQB8gQT8gHyEfISAgICAgIB8gIEAgIEAfICAgICAgICEfIB8hICAfICAgICAfIR8hICEfICAgHyEfQD8hYoFAICBAQCEeISAgICAfIR8hHyAfQSAhPiEfICEfISAeISAgHyEgICAfICAgICAgICEeIR8iHiEgICA/QCFggz8gIEA/Ih4hICAfICAgISAfICBBHyA/ISAfICAgICAgICEeIR8iHyAgIB8gISAeISAhHyEeIR8gIEBAIIEADQUAAAAAAAAAAAAA'

  - platform: broadlink
    host: 10.100.102.23
    mac: '34:ea:34:42:bb:86'
    type: rm_mini
    switches:
      play_room_air_con:
        friendly_name: "Play Room Air Condition"
#heat
        command_on: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
        command_off: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
#cold
#        command_on: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
#        command_off: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
    
  - platform: broadlink
    host: 10.100.102.29
    mac: '78:0f:77:17:e8:3a'
    type: rm2_pro_plus
    switches:
      play_room_air_con:
        friendly_name: "Play Room Air Condition"
#heat
        command_on: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
        command_off: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
#cold
#        command_on: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='
#        command_off: 'JgBgAQABKpIWNRU1FhAVERURFRAWEBU2FREVNRY1FREVEBYQFREVERUQFjUVNhUQFhAVERURFRAWEBU2FRAWEBU2FREVEBYQFREVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBURFREVAAEEFjQWNRURFRAWNRURFREVNRY1FREVNRYQFhAVERUQFhAWEBURFRAWEBURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFREVEBYQFhAVERUQFhAVERURFRAWEBURFTUWEBYQFREVEBYQFTYVAAEEFhAVEBYQFREVEBYQFREVERU1FhAVERUQFhAVERURFRAWEBURFREVEBYQFREVEBYQFhAVERUQFhAVERUQFhAVERURFRAWEBURFRAWEBYQFREVEBYQFREVERUQFhAVERURFTUWEBURFRAWEBURFRAWEBUADQUAAAAAAAAAAA=='

    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
zone: !include zones.yaml
