homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    switch:
      assumed_state: true

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

ios:

http:
  api_password: !secret http_password
  base_url: https://yedgar.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Cloud
cloud:

api:

vera:
  vera_controller_url: http://10.100.102.200:3480
  
mqtt:
  broker: m23.cloudmqtt.com
  port: 16080
  username: !secret mqtt_user
  password: !secret mqtt_password

#telegram  
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_chat

notify:
  - name: bot_bot
    platform: telegram
    chat_id: !secret telegram_chat
#end telegram

input_number:
  aircon_number:
    name: aircon_number
    initial: 27
    min: 24
    max: 30
    step: 1
    
lovelace:
  mode: storage

weather:
  - platform: darksky
    api_key: e2b5eb70a7057bca2afb537bd0b62f28

prometheus:
  namespace: homeassistant
   

switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
zone: !include zones.yaml
