title: My Awesome Home
views:
    # View tab title.
  - title: Example
    panel: true
    # Makes the first card fill the view
    cards:
      - type: picture-elements
        image: /local/first.jpg
        panel: true
        elements:
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_4
            style:
              top: 25%
              left: 28%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch
            style:
              top: 56%
              left: 30%
              width: 5%
            state_image:
              "on": /local/wall-on.png
              "off": /local/wall-off.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_3
            style:
              top: 50%
              left: 55%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_6
            style:
              top: 35%
              left: 55%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png   
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_9
            style:
              top: 5%
              left: 78%
              width: 7%
              height: 3%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png 
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_10
            style:
              top: 26%
              left: 90%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
            style:
              top: 8%
              left: 31%
              width: 14%
              height: 3%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_7
            style:
              top: 30%
              left: 10%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_5
            style:
              top: 56%
              left: 10%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_6
            style:
              top: 82%
              left: 10%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: switch.living_room_air_con
            tap_action: toggle
            style:
              top: 8%
              left: 45%
              width: 10%
            state_image:
              "on": /local/aircon-on.png
              "off": /local/aircon-off.png
        - type: horizontal-stack
          id: 123
          cards:
            - type: entity-button
              entity: scene.first_floor_a_bit
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.first_floor_50
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.close_first_floor
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.first_floor_a_bit
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.first_floor_50
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.close_first_floor
              tap_action: scene.turn_on
