title: My Awesome Home
views:
    # View tab title.
  - title: Example
    panel: true
    # Makes the first card fill the view
    cards:
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: scene.first_floor_a_bit
            - type: entity-button
              entity: scene.first_floor_50
            - type: entity-button
              entity: scene.close_first_floor
