title: My Awesome Home
views:
  - title: first
    cards:
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - switch.living_room_air_con
          - switch.parents_air_con
          - switch.kids_air_con
    # View tab title.
  - title: Example
    # panel: true
    # Makes the first card fill the view
    cards:
      - type: picture-elements
        image: /local/first.jpg
        elements:
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_4
            style:
              top: 25%
              left: 28%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            tap_action: toggle
            entity: switch.bathroom_wall_light_41
            style:
              top: 56%
              left: 30%
              width: 5%
            state_image:
              "on": /local/wall-on.png
              "off": /local/wall-off.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_3
            style:
              top: 50%
              left: 55%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_6
            style:
              top: 35%
              left: 55%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png   
          - type: image
            entity: cover.kitchen_roller_left_14
            style:
              top: 5%
              left: 78%
              width: 7%
              height: 3%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png 
          - type: image
            entity: cover.kitchen_roller_right_15
            style:
              top: 26%
              left: 90%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.living_room_big_roller_18
            style:
              top: 8%
              left: 31%
              width: 14%
              height: 3%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.living_room_roller_right_19
            style:
              top: 30%
              left: 10%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.living_room_roller_middle_16
            style:
              top: 56%
              left: 10%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.living_room_roller_left_17
            style:
              top: 82%
              left: 10%
              width: 5%
              height: 15%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: switch.living_room_air_con
            tap_action: toggle
            style:
              top: 8%
              left: 45%
              width: 10%
            state_image:
              "on": /local/aircon-on.png
              "off": /local/aircon-off.png
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: scene.first_floor_a_bit
            tap_action: call-service
            service: scene.turn_on
          - type: entity-button
            entity: scene.first_floor_50
            tap_action: scene.turn_on
          - type: entity-button
            entity: scene.close_first_floor
            tap_action: scene.turn_on
          - type: entity-button
            entity: scene.first_floor_a_bit
            tap_action: scene.turn_on
          - type: entity-button
            entity: scene.first_floor_50
            tap_action: scene.turn_on
          - type: entity-button
            entity: scene.close_first_floor
            tap_action: scene.turn_on
        