title: My Awesome Home
views:
    # View tab title.
  - title: Example
    # Makes the first card fill the view
    cards:
      - type: picture-entity
        entity: switch.living_room_ceiling_light_40
        image: http://farm7.static.flickr.com/6153/6220100622_88e64ec5d8_b.jpg
        state_image:
          "on": http://farm7.static.flickr.com/6220/6220100616_a877f41a66_b.jpg
        title: Livingroom lights
        tap_action: toggle
        