title: My Awesome Home
views:
    # View tab title.
  - title: Example
    panel: true
    # Makes the first card fill the view
    cards:
        - type: horizontal-stack
          id: 123
          cards:
            - type: entity-button
              entity: scene.first_floor_a_bit
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.first_floor_50
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.close_first_floor
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.first_floor_a_bit
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.first_floor_50
              tap_action: scene.turn_on
            - type: entity-button
              entity: scene.close_first_floor
              tap_action: scene.turn_on
